In [3]:
import numpy as np

In [2]:
pip install numpy

                                              0.0/15.5 MB ? eta -:--:--
                                              0.2/15.5 MB 3.5 MB/s eta 0:00:05
                                              0.4/15.5 MB 3.8 MB/s eta 0:00:04
     -                                        0.6/15.5 MB 4.3 MB/s eta 0:00:04
     --                                       0.8/15.5 MB 4.4 MB/s eta 0:00:04
     --                                       1.1/15.5 MB 4.7 MB/s eta 0:00:04
     ---                                      1.4/15.5 MB 4.8 MB/s eta 0:00:03
     ----                                     1.6/15.5 MB 4.9 MB/s eta 0:00:03
     ----                                     1.9/15.5 MB 4.8 MB/s eta 0:00:03
     -----                                    2.1/15.5 MB 4.7 MB/s eta 0:00:03
     -----                                    2.3/15.5 MB 4.7 MB/s eta 0:00:03
     ------                                   2.5/15.5 MB 4.8 MB/s eta 0:00:03
     -------                                  2.8/15.5 MB 4

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mylist=[1,3,434,434]
narr=np.array(mylist)

In [8]:
narr

array([  1,   3, 434, 434])

In [9]:
narr.shape

(4,)

In [10]:
mylist1=[[1,2,3,4],[4,5,6,7],[42,4,54,5]]
narr1=np.array(mylist1)
narr1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [42,  4, 54,  5]])

In [11]:
narr1.shape

(3, 4)

In [12]:
type(narr1)

numpy.ndarray

In [13]:
narr1.dtype

dtype('int32')

In [14]:
narr1.reshape

<function ndarray.reshape>

In [15]:
np.random.rand(3)

array([0.49901848, 0.88374397, 0.11673406])

In [16]:
np.random.rand(3,4,5)

array([[[0.8175117 , 0.60710495, 0.34789177, 0.32985412, 0.04732834],
        [0.57008307, 0.17005665, 0.85617098, 0.94867683, 0.10571302],
        [0.73928577, 0.6234709 , 0.95580603, 0.95045408, 0.81616069],
        [0.79937304, 0.23616533, 0.0444941 , 0.95154885, 0.23610556]],

       [[0.58277537, 0.69846074, 0.00257551, 0.63043447, 0.2378578 ],
        [0.85978629, 0.1660736 , 0.64502751, 0.24329314, 0.87357024],
        [0.81609243, 0.07783603, 0.67550468, 0.96733656, 0.381571  ],
        [0.16668002, 0.37891789, 0.24631798, 0.11400358, 0.669473  ]],

       [[0.14792268, 0.44349916, 0.44535158, 0.42323315, 0.43430448],
        [0.67718399, 0.2125477 , 0.25821618, 0.02583471, 0.04251907],
        [0.55925985, 0.90472065, 0.13561733, 0.99811662, 0.09223035],
        [0.09237947, 0.7290497 , 0.49283672, 0.88547307, 0.20892398]]])